### ISSUE TITLE
License of this repository

### ISSUE THREAD

**Issue by D0rs4n** [rglsk/fastapi-sqlalchemy-1.4-async#1]
Hi! 
The tutorial code is pretty straightforward, and was a great start on this pretty hard topic. (Mostly the testing part)
Although, I noticed that there is no explicit license on this repository, and I'm curious as to which license is this repository, in case I would like to use it.
Thank you for your work! 👍 
@rglsk

**Comment by rglsk** [comment]
Hey @D0rs4n, thanks for reporting, I will add it soon!
