### ISSUE TITLE
[Question] Joining Tables in Repository Pattern

### ISSUE THREAD

**Issue by jabertuhin** [rglsk/fastapi-sqlalchemy-1.4-async#3]
Hello @rglsk , thanks for the blog post. It really helped me to implement the repository pattern, and learn about some other useful stuffs.

I was wondering, how can I join two tables in this setup? Do you have any plan to update the repository/blog post with such an example?
Can you share any resources with me from where I can get help?

Thanks in advance.

**Comment by rglsk** [comment]
Hey, thanks for a question!


>  Do you have any plan to update the repository/blog post with such an example?
Not at the moment, sorry :/

> I was wondering, how can I join two tables in this setup?
Would [this](https://docs.sqlalchemy.org/en/14/orm/join_conditions.html) be helpful? Just add a relations to tables and perform a join operation 🤔 

Please let me know @jabertuhin if this is helpful for you :)

**Comment by jabertuhin** [comment]
Thanks for the reply.

My confusion was about - where that join operation will go?

In this codebase, we have `BaseRepository` and `CouponsRepository` which implements `BaseRepository`. We can't handle all kinds of join operation via `BaseRepository`, and `BaseRepository` won't have information of multiple tables. 

If `Coupon` table has a relationship with another(ex. `User`) table, and I want to join `User` table with coupon table, where will the code for that operation go? Under `CouponsRepository`?

**Comment by rglsk** [comment]
Ah got it now, great question. I've been always adding it to the one of them based on which join it is, but I think it does not matter to which one. Just add a good name like `def get_coupons_with_users(...)`. In most cases you will have one domain more important than another (maybe a left or right joint) then you can place it there. Hope that is helpful :)

**Comment by jabertuhin** [comment]
Thanks, it was helpful.
